// src/adapters/vue/components/Calendar.vue
<template>
  <div ref="calendarRef" class="ldesign-calendar-wrapper"></div>
</template>

<script setup lang="ts">
import { ref, onMounted, watch, onBeforeUnmount } from 'vue';
import { Calendar } from '../../../core/calendar';
import type { CalendarConfig, CalendarEvent, CalendarView } from '../../../types';

// Props
const props = withDefaults(defineProps<{
  config?: CalendarConfig;
  events?: CalendarEvent[];
}>(), {
  config: () => ({}),
  events: () => [],
});

// Emits
const emit = defineEmits<{
  eventClick: [event: CalendarEvent];
  eventCreate: [event: CalendarEvent];
  eventUpdate: [event: CalendarEvent, oldEvent: CalendarEvent];
  eventDelete: [id: string];
  dateSelect: [start: Date, end: Date];
  dateClick: [date: Date];
  viewChange: [view: CalendarView, date: Date];
  eventDragStart: [event: CalendarEvent];
  eventDragEnd: [event: CalendarEvent];
  eventResizeStart: [event: CalendarEvent];
  eventResizeEnd: [event: CalendarEvent];
}>();

// Refs
const calendarRef = ref<HTMLElement>();
let calendar: Calendar | null = null;

// 初始化
onMounted(() => {
  if (!calendarRef.value) return;

  // 创建日历实例
  calendar = new Calendar(calendarRef.value, props.config);

  // 绑定事件
  calendar.on('eventClick', (event: CalendarEvent) => emit('eventClick', event));
  calendar.on('eventCreate', (event: CalendarEvent) => emit('eventCreate', event));
  calendar.on('eventUpdate', (event: CalendarEvent, oldEvent: CalendarEvent) =>
    emit('eventUpdate', event, oldEvent)
  );
  calendar.on('eventDelete', (id: string) => emit('eventDelete', id));
  calendar.on('dateSelect', (start: Date, end: Date) => emit('dateSelect', start, end));
  calendar.on('dateClick', (date: Date) => emit('dateClick', date));
  calendar.on('viewChange', (view: CalendarView, date: Date) =>
    emit('viewChange', view, date)
  );
  calendar.on('eventDragStart', (event: CalendarEvent) => emit('eventDragStart', event));
  calendar.on('eventDragEnd', (event: CalendarEvent) => emit('eventDragEnd', event));
  calendar.on('eventResizeStart', (event: CalendarEvent) =>
    emit('eventResizeStart', event)
  );
  calendar.on('eventResizeEnd', (event: CalendarEvent) => emit('eventResizeEnd', event));

  // 添加初始事件
  if (props.events && props.events.length > 0) {
    props.events.forEach(event => {
      calendar?.addEvent(event);
    });
  }
});

// 监听事件变化
watch(
  () => props.events,
  (newEvents) => {
    if (calendar && newEvents) {
      // TODO: 智能更新事件（diff算法）
      calendar.render();
    }
  },
  { deep: true }
);

// 清理
onBeforeUnmount(() => {
  if (calendar) {
    calendar.destroy();
    calendar = null;
  }
});

// 暴露方法给父组件
defineExpose({
  getCalendar: () => calendar,
  addEvent: (event: Omit<CalendarEvent, 'id'>) => calendar?.addEvent(event),
  updateEvent: (id: string, updates: Partial<CalendarEvent>) =>
    calendar?.updateEvent(id, updates),
  deleteEvent: (id: string) => calendar?.deleteEvent(id),
  getEvents: (start?: Date, end?: Date) => calendar?.getEvents(start, end),
  changeView: (view: CalendarView) => calendar?.changeView(view),
  next: () => calendar?.next(),
  prev: () => calendar?.prev(),
  today: () => calendar?.today(),
  gotoDate: (date: Date) => calendar?.gotoDate(date),
});
</script>

<style>
.ldesign-calendar-wrapper {
  width: 100%;
  height: 100%;
}
</style>

// src/adapters/react/components/Calendar.tsx
/**
 * @ldesign/calendar - React 组件
 */

import React, { useRef, useEffect, useImperativeHandle, forwardRef } from 'react';
import { Calendar as CalendarCore } from '../../../core/calendar';
import type { CalendarConfig, CalendarEvent, CalendarView } from '../../../types';

export interface CalendarProps {
  config?: CalendarConfig;
  events?: CalendarEvent[];
  onEventClick?: (event: CalendarEvent) => void;
  onEventCreate?: (event: CalendarEvent) => void | boolean | Promise<void | boolean>;
  onEventUpdate?: (event: CalendarEvent, oldEvent: CalendarEvent) => void | boolean | Promise<void | boolean>;
  onEventDelete?: (id: string) => void | boolean | Promise<void | boolean>;
  onDateSelect?: (start: Date, end: Date) => void;
  onDateClick?: (date: Date) => void;
  onViewChange?: (view: CalendarView, date: Date) => void;
  onEventDragStart?: (event: CalendarEvent) => void;
  onEventDragEnd?: (event: CalendarEvent) => void;
  onEventResizeStart?: (event: CalendarEvent) => void;
  onEventResizeEnd?: (event: CalendarEvent) => void;
  className?: string;
  style?: React.CSSProperties;
}

export interface CalendarRef {
  getCalendar: () => CalendarCore | null;
  addEvent: (event: Omit<CalendarEvent, 'id'>) => Promise<string>;
  updateEvent: (id: string, updates: Partial<CalendarEvent>) => Promise<void>;
  deleteEvent: (id: string) => Promise<void>;
  getEvents: (start?: Date, end?: Date) => CalendarEvent[];
  changeView: (view: CalendarView) => void;
  next: () => void;
  prev: () => void;
  today: () => void;
  gotoDate: (date: Date) => void;
}

export const Calendar = forwardRef<CalendarRef, CalendarProps>((props, ref) => {
  const {
    config = {},
    events = [],
    onEventClick,
    onEventCreate,
    onEventUpdate,
    onEventDelete,
    onDateSelect,
    onDateClick,
    onViewChange,
    onEventDragStart,
    onEventDragEnd,
    onEventResizeStart,
    onEventResizeEnd,
    className,
    style,
  } = props;

  const containerRef = useRef<HTMLDivElement>(null);
  const calendarRef = useRef<CalendarCore | null>(null);

  // 初始化
  useEffect(() => {
    if (!containerRef.current) return;

    // 创建日历实例
    calendarRef.current = new CalendarCore(containerRef.current, config);

    // 绑定事件
    if (onEventClick) {
      calendarRef.current.on('eventClick', onEventClick);
    }
    if (onEventCreate) {
      calendarRef.current.on('eventCreate', onEventCreate);
    }
    if (onEventUpdate) {
      calendarRef.current.on('eventUpdate', onEventUpdate);
    }
    if (onEventDelete) {
      calendarRef.current.on('eventDelete', onEventDelete);
    }
    if (onDateSelect) {
      calendarRef.current.on('dateSelect', onDateSelect);
    }
    if (onDateClick) {
      calendarRef.current.on('dateClick', onDateClick);
    }
    if (onViewChange) {
      calendarRef.current.on('viewChange', onViewChange);
    }
    if (onEventDragStart) {
      calendarRef.current.on('eventDragStart', onEventDragStart);
    }
    if (onEventDragEnd) {
      calendarRef.current.on('eventDragEnd', onEventDragEnd);
    }
    if (onEventResizeStart) {
      calendarRef.current.on('eventResizeStart', onEventResizeStart);
    }
    if (onEventResizeEnd) {
      calendarRef.current.on('eventResizeEnd', onEventResizeEnd);
    }

    // 添加初始事件
    if (events && events.length > 0) {
      events.forEach(event => {
        calendarRef.current?.addEvent(event);
      });
    }

    // 清理
    return () => {
      if (calendarRef.current) {
        calendarRef.current.destroy();
        calendarRef.current = null;
      }
    };
  }, []);

  // 监听事件变化
  useEffect(() => {
    if (calendarRef.current && events) {
      // TODO: 智能更新事件（diff算法）
      calendarRef.current.render();
    }
  }, [events]);

  // 暴露方法
  useImperativeHandle(ref, () => ({
    getCalendar: () => calendarRef.current,
    addEvent: async (event: Omit<CalendarEvent, 'id'>) => {
      if (!calendarRef.current) {
        throw new Error('Calendar not initialized');
      }
      return await calendarRef.current.addEvent(event);
    },
    updateEvent: async (id: string, updates: Partial<CalendarEvent>) => {
      if (!calendarRef.current) {
        throw new Error('Calendar not initialized');
      }
      await calendarRef.current.updateEvent(id, updates);
    },
    deleteEvent: async (id: string) => {
      if (!calendarRef.current) {
        throw new Error('Calendar not initialized');
      }
      await calendarRef.current.deleteEvent(id);
    },
    getEvents: (start?: Date, end?: Date) => {
      if (!calendarRef.current) {
        return [];
      }
      return calendarRef.current.getEvents(start, end);
    },
    changeView: (view: CalendarView) => {
      calendarRef.current?.changeView(view);
    },
    next: () => {
      calendarRef.current?.next();
    },
    prev: () => {
      calendarRef.current?.prev();
    },
    today: () => {
      calendarRef.current?.today();
    },
    gotoDate: (date: Date) => {
      calendarRef.current?.gotoDate(date);
    },
  }));

  return (
    <div
      ref={containerRef}
      className={`ldesign-calendar-wrapper ${className || ''}`}
      style={style}
    />
  );
});

Calendar.displayName = 'Calendar';
